### ISSUE TITLE
New to ReactJS. Having trouble with using Hook inside a function components

### ISSUE THREAD

**Issue by tretrautroll2** [tretrautroll2/Projectfoodweb#1]
Im developing a test project, the goal is to create a shopping cart. I created a Navbar which filter out the type of items and render it. I want to add a Modal to each items created but using useState but it turns out to return an error:

The Modal function is located in ItemInteract.js file 
i imported that function in ./Pages/Food.js to use it as a onClick function 
it returns the error

Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (http://localhost:3000/static/js/bundle.js:20032:13)
    at useState (http://localhost:3000/static/js/bundle.js:35699:25)
    at ItemDescription (http://localhost:3000/static/js/bundle.js:734:84)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:10355:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:10399:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:10456:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:10470:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:14613:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:14639:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:14650:9)

**Comment by vsnikhilvs** [comment]
You might have called a hook inside another function.
Hooks should be called independently, means outside the function

**Comment by tretrautroll2** [comment]
So is there a suggestion for approaching method sir

**Comment by vsnikhilvs** [comment]
Upon checking your code, you are passing a component into the onClick function, where a click function is expected.
If you need a modal on clicking an item, you should write a state that changes some variable say, `showModal` and upon it being true, you can show the modal like:
```
{
  showModal && <ModalComponent />
}
```
